export const Kidsproducts = [
  {
    id: 200,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys1.avif"),
    Desc: "Stylish Boy's Set",
    Price: 850,
  },
  {
    id: 201,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls1.avif"),
    Desc: "Stylish Girl's Set",
    Price: 399,
  },
  {
    id: 202,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys2.avif"),
    Desc: "Stylish Boy's Set",
    Price: 850,
  },
  {
    id: 203,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls2.avif"),
    Desc: "Stylish Girl's Set",
    Price: 399,
  },
  {
    id: 104,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys3.avif"),
    Desc: "Stylish Boy's Set",
    Price: 850,
  },
  {
    id: 105,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls3.avif"),
    Desc: "Stylish Girl's Set",
    Price: 399,
  },
  {
    id: 206,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys4.avif"),
    Desc: "Stylish Boy's Set",
    Price: 850,
  },
  {
    id: 207,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls4.avif"),
    Desc: "Stylish Girl's Set",
    Price: 249,
  },
  {
    id: 208,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys5.avif"),
    Desc: "Stylish Boy's Set",
    Price: 850,
  },
  {
    id: 209,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls5.avif"),
    Desc: "Stylish Girl's Set",
    Price: 329,
  },
  {
    id: 210,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys6.avif"),
    Desc: "Stylish Boy's Set",
    Price: 850,
  },
  {
    id: 211,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls6.avif"),
    Desc: "Stylish Girl's Set",
    Price: 220,
  },
  {
    id: 212,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys7.jpg"),
    Desc: "Stylish Boy's Set",
    Price: 1000,
  },
  {
    id: 213,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls7.avif"),
    Desc: "Stylish Girl's Set",
    Price: 650,
  },
  {
    id: 214,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys8.avif"),
    Desc: "Stylish Boy's Set",
    Price: 450,
  },
  {
    id: 215,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls8.avif"),
    Desc: "Stylish Girl's Set",
    Price: 320,
  },
  {
    id: 216,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys9.avif"),
    Desc: "Stylish Boy's Set",
    Price: 870,
  },
  {
    id: 217,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls9.jpg"),
    Desc: "Stylish Girl's Set",
    Price: 620,
  },
  {
    id: 218,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys10.avif"),
    Desc: "Stylish Boy's Set",
    Price: 450,
  },
  {
    id: 219,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls10.avif"),
    Desc: "Stylish Girl's Set",
    Price: 340,
  },
  {
    id: 220,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys11.avif"),
    Desc: "Stylish Boy's Set",
    Price: 720,
  },
  {
    id: 221,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls11.jpg"),
    Desc: "Stylish Girl's Set",
    Price: 280,
  },
  {
    id: 222,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys12.avif"),
    Desc: "Stylish Boy's Set",
    Price: 670,
  },
  {
    id: 223,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls12.avif"),
    Desc: "Stylish Girl's Set",
    Price: 750,
  },
  {
    id: 224,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys13.avif"),
    Desc: "Stylish Boy's Set",
    Price: 420,
  },
  {
    id: 225,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls13.avif"),
    Desc: "Stylish Girl's Set",
    Price: 700,
  },
  {
    id: 226,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys14.jpg"),
    Desc: "Stylish Boy's Set",
    Price: 240,
  },
  {
    id: 227,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls14.avif"),
    Desc: "Stylish Girl's Set",
    Price: 340,
  },
  {
    id: 228,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys15.avif"),
    Desc: "Stylish Boy's Set",
    Price: 450,
  },
  {
    id: 229,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls15.avif"),
    Desc: "Stylish Girl's Set",
    Price: 520,
  },
  {
    id: 230,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys16.avif"),
    Desc: "Stylish Boy's Set",
    Price: 630,
  },
  {
    id: 231,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls16.avif"),
    Desc: "Stylish Girl's Set",
    Price: 470,
  },
  {
    id: 232,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys17.avif"),
    Desc: "Stylish Boy's Set",
    Price: 520,
  },
  {
    id: 233,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls17.avif"),
    Desc: "Stylish Girl's Set",
    Price: 470,
  },
  {
    id: 234,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys18.jpg"),
    Desc: "Stylish Boy's Set",
    Price: 750,
  },
  {
    id: 235,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls18.avif"),
    Desc: "Stylish Girl's Set",
    Price: 470,
  },
  {
    id: 236,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys19.avif"),
    Desc: "Stylish Boy's Set",
    Price: 640,
  },
  {
    id: 237,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls19.avif"),
    Desc: "Stylish Girl's Set",
    Price: 540,
  },
  {
    id: 238,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys20.avif"),
    Desc: "Stylish Boy's Set",
    Price: 986,
  },
  {
    id: 239,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls20.avif"),
    Desc: "Stylish Girl's Set",
    Price: 567,
  },
  {
    id: 240,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys21.avif"),
    Desc: "Stylish Boy's Set",
    Price: 945,
  },
  {
    id: 241,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls21.avif"),
    Desc: "Stylish Girl's Set",
    Price: 453,
  },
  {
    id: 242,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys22.jpg"),
    Desc: "Stylish Boy's Set",
    Price: 365,
  },
  {
    id: 243,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls22.avif"),
    Desc: "Stylish Girl's Set",
    Price: 296,
  },
  {
    id: 244,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys23.avif"),
    Desc: "Stylish Boy's Set",
    Price: 864,
  },
  {
    id: 245,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls23.avif"),
    Desc: "Stylish Girl's Set",
    Price: 543,
  },
  {
    id: 246,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys24.avif"),
    Desc: "Stylish Boy's Set",
    Price: 432,
  },
  {
    id: 247,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls13.avif"),
    Desc: "Stylish Girl's Set",
    Price: 321,
  },
  {
    id: 248,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys14.jpg"),
    Desc: "Stylish Boy's Set",
    Price: 450,
  },
  {
    id: 249,
    title: "Girls's Set",
    image: require("../../assets/images/Kids/girls10.avif"),
    Desc: "Stylish Girl's Set",
    Price: 678,
  },
  {
    id: 250,
    title: "Boy's Set",
    image: require("../../assets/images/Kids/boys18.jpg"),
    Desc: "Stylish Boy's Set",
    Price: 345,
  },
  //   {
  //     id: 151,
  //     title: "Jacket",
  //     image: require("../../assets/images/Womens/products/Jacket13.avif"),
  //     Desc: "Stylish Women's Jackets",
  //     Price: 234,
  //   },
  //   {
  //     id: 152,
  //     title: "Saree",
  //     image: require("../../assets/images/Womens/products/saree14.jpg"),
  //     Desc: "Stylish Women's Saree",
  //     Price: 745,
  //   },
  //   {
  //     id: 153,
  //     title: "Lehanga",
  //     image: require("../../assets/images/Womens/products/lehanga14.jpg"),
  //     Desc: "Stylish Women's Lehanga",
  //     Price: 397,
  //   },
  //   {
  //     id: 154,
  //     title: "Top",
  //     image: require("../../assets/images/Womens/products/Top14.avif"),
  //     Desc: "Stylish Women's Top",
  //     Price: 490,
  //   },
  //   {
  //     id: 155,
  //     title: "Jacket",
  //     image: require("../../assets/images/Womens/products/Jacket14.avif"),
  //     Desc: "Stylish Women's Jackets",
  //     Price: 540,
  //   },
  //   {
  //     id: 156,
  //     title: "Saree",
  //     image: require("../../assets/images/Womens/products/saree15.avif"),
  //     Desc: "Stylish Women's Saree",
  //     Price: 947,
  //   },
  //   {
  //     id: 157,
  //     title: "Lehanga",
  //     image: require("../../assets/images/Womens/products/lehanga15.webp"),
  //     Desc: "Stylish Women's Lehanga",
  //     Price: 429,
  //   },
  //   {
  //     id: 158,
  //     title: "Top",
  //     image: require("../../assets/images/Womens/products/Top15.jpg"),
  //     Desc: "Stylish Women's Top",
  //     Price: 398,
  //   },
  //   {
  //     id: 159,
  //     title: "Jacket",
  //     image: require("../../assets/images/Womens/products/Jacket15.webp"),
  //     Desc: "Stylish Women's Jackets",
  //     Price: 298,
  //   },
  //   {
  //     id: 160,
  //     title: "Saree",
  //     image: require("../../assets/images/Womens/products/saree16.jpg"),
  //     Desc: "Stylish Women's Saree",
  //     Price: 789,
  //   },
  //   {
  //     id: 161,
  //     title: "Lehanga",
  //     image: require("../../assets/images/Womens/products/lehanga16.avif"),
  //     Desc: "Stylish Women's Lehanga",
  //     Price: 480,
  //   },
  //   {
  //     id: 162,
  //     title: "Top",
  //     image: require("../../assets/images/Womens/products/Top16.avif"),
  //     Desc: "Stylish Women's Top",
  //     Price: 730,
  //   },
  //   {
  //     id: 163,
  //     title: "Jacket",
  //     image: require("../../assets/images/Womens/products/Jacket16.avif"),
  //     Desc: "Stylish Women's Jackets",
  //     Price: 830,
  //   },
  //   {
  //     id: 164,
  //     title: "Saree",
  //     image: require("../../assets/images/Womens/products/saree17.avif"),
  //     Desc: "Stylish Women's Saree",
  //     Price: 950,
  //   },
  //   {
  //     id: 165,
  //     title: "Lehanga",
  //     image: require("../../assets/images/Womens/products/lehanga17.avif"),
  //     Desc: "Stylish Women's Lehanga",
  //     Price: 639,
  //   },
  //   {
  //     id: 166,
  //     title: "Top",
  //     image: require("../../assets/images/Womens/products/Top17.avif"),
  //     Desc: "Stylish Women's Top",
  //     Price: 920,
  //   },
  //   {
  //     id: 167,
  //     title: "Jacket",
  //     image: require("../../assets/images/Womens/products/Jacket17.webp"),
  //     Desc: "Stylish Women's Jackets",
  //     Price: 850,
  //   },
  //   {
  //     id: 168,
  //     title: "Saree",
  //     image: require("../../assets/images/Womens/products/saree18.avif"),
  //     Desc: "Stylish Women's Saree",
  //     Price: 849,
  //   },
  //   {
  //     id: 169,
  //     title: "Lehanga",
  //     image: require("../../assets/images/Womens/products/lehanga18.avif"),
  //     Desc: "Stylish Women's Lehanga",
  //     Price: 940,
  //   },
  //   {
  //     id: 170,
  //     title: "Top",
  //     image: require("../../assets/images/Womens/products/Top18.avif"),
  //     Desc: "Stylish Women's Top",
  //     Price: 940,
  //   },
  //   {
  //     id: 171,
  //     title: "Jacket",
  //     image: require("../../assets/images/Womens/products/Jacket18.avif"),
  //     Desc: "Stylish Women's Jackets",
  //     Price: 298,
  //   },
  //   {
  //     id: 172,
  //     title: "Saree",
  //     image: require("../../assets/images/Womens/products/saree19.avif"),
  //     Desc: "Stylish Women's Saree",
  //     Price: 678,
  //   },
  //   {
  //     id: 173,
  //     title: "Lehanga",
  //     image: require("../../assets/images/Womens/products/lehanga19.webp"),
  //     Desc: "Stylish Women's Lehanga",
  //     Price: 840,
  //   },
  //   {
  //     id: 174,
  //     title: "Top",
  //     image: require("../../assets/images/Womens/products/Top19.avif"),
  //     Desc: "Stylish Women's Top",
  //     Price: 780,
  //   },
  //   {
  //     id: 175,
  //     title: "Jacket",
  //     image: require("../../assets/images/Womens/products/Jacket19.avif"),
  //     Desc: "Stylish Women's Jackets",
  //     Price: 930,
  //   },
  //   {
  //     id: 176,
  //     title: "Saree",
  //     image: require("../../assets/images/Womens/products/saree20.avif"),
  //     Desc: "Stylish Women's Saree",
  //     Price: 948,
  //   },
  //   {
  //     id: 177,
  //     title: "Lehanga",
  //     image: require("../../assets/images/Womens/products/lehanga20.avif"),
  //     Desc: "Stylish Women's Lehanga",
  //     Price: 928,
  //   },
  //   {
  //     id: 178,
  //     title: "Top",
  //     image: require("../../assets/images/Womens/products/Top20.avif"),
  //     Desc: "Stylish Women's Top",
  //     Price: 748,
  //   },
  //   {
  //     id: 179,
  //     title: "Jacket",
  //     image: require("../../assets/images/Womens/products/Jacket20.avif"),
  //     Desc: "Stylish Women's Jackets",
  //     Price: 564,
  //   },
  //   {
  //     id: 180,
  //     title: "Saree",
  //     image: require("../../assets/images/Womens/products/saree21.avif"),
  //     Desc: "Stylish Women's Saree",
  //     Price: 879,
  //   },
  //   {
  //     id: 181,
  //     title: "Lehanga",
  //     image: require("../../assets/images/Womens/products/lehanga21.avif"),
  //     Desc: "Stylish Women's Lehanga",
  //     Price: 299,
  //   },
  //   {
  //     id: 182,
  //     title: "Top",
  //     image: require("../../assets/images/Womens/products/Top21.avif"),
  //     Desc: "Stylish Women's Top",
  //     Price: 845,
  //   },
  //   {
  //     id: 183,
  //     title: "Jacket",
  //     image: require("../../assets/images/Womens/products/jacket21.avif"),
  //     Desc: "Stylish Women's Jackets",
  //     Price: 907,
  //   },
  //   {
  //     id: 184,
  //     title: "Saree",
  //     image: require("../../assets/images/Womens/products/saree22.avif"),
  //     Desc: "Stylish Women's Saree",
  //     Price: 748,
  //   },
  //   {
  //     id: 185,
  //     title: "Lehanga",
  //     image: require("../../assets/images/Womens/products/lehanga22.avif"),
  //     Desc: "Stylish Women's Lehanga",
  //     Price: 936,
  //   },
  //   {
  //     id: 186,
  //     title: "Top",
  //     image: require("../../assets/images/Womens/products/Top22.jpg"),
  //     Desc: "Stylish Women's Top",
  //     Price: 573,
  //   },
  //   {
  //     id: 187,
  //     title: "Jacket",
  //     image: require("../../assets/images/Womens/products/jacket22.webp"),
  //     Desc: "Stylish Women's Jackets",
  //     Price: 298,
  //   },
  //   {
  //     id: 188,
  //     title: "Saree",
  //     image: require("../../assets/images/Womens/products/saree23.avif"),
  //     Desc: "Stylish Women's Saree",
  //     Price: 639,
  //   },
  //   {
  //     id: 189,
  //     title: "Lehanga",
  //     image: require("../../assets/images/Womens/products/lehanga23.avif"),
  //     Desc: "Stylish Women's Lehanga",
  //     Price: 599,
  //   },
  //   {
  //     id: 190,
  //     title: "Top",
  //     image: require("../../assets/images/Womens/products/Top23.avif"),
  //     Desc: "Stylish Women's Top",
  //     Price: 300,
  //   },
  //   {
  //     id: 191,
  //     title: "Jacket",
  //     image: require("../../assets/images/Womens/products/jacket23.avif"),
  //     Desc: "Stylish Women's Jackets",
  //     Price: 450,
  //   },
  //   {
  //     id: 192,
  //     title: "Saree",
  //     image: require("../../assets/images/Womens/products/saree24.webp"),
  //     Desc: "Stylish Women's Saree",
  //     Price: 739,
  //   },
  //   {
  //     id: 193,
  //     title: "Lehanga",
  //     image: require("../../assets/images/Womens/products/lehanga24.avif"),
  //     Desc: "Stylish Women's Lehanga",
  //     Price: 938,
  //   },
  //   {
  //     id: 194,
  //     title: "Top",
  //     image: require("../../assets/images/Womens/products/Top24.webp"),
  //     Desc: "Stylish Women's Top",
  //     Price: 394,
  //   },
  //   {
  //     id: 195,
  //     title: "Jacket",
  //     image: require("../../assets/images/Womens/products/jacket24.avif"),
  //     Desc: "Stylish Women's Jackets",
  //     Price: 310,
  //   },
];
