export const Mensproducts = [
  {
    id: 1,
    title: "shirt",
    image: require("../../assets/images/Mens/products/men1.avif"),
    Desc: "Stylish Men's Shirt",
    Price: 850,
  },
  {
    id: 2,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/t-shirt1.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 399,
  },
  {
    id: 3,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant1.avif"),
    Desc: "Stylish Men's Pant",
    Price: 499,
  },
  {
    id: 4,
    title: "short",
    image: require("../../assets/images/Mens/products/short1.webp"),
    Desc: "Stylish Men's Short",
    Price: 299,
  },
  {
    id: 5,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt2.webp"),
    Desc: "Stylish Men's Shirt",
    Price: 830,
  },
  {
    id: 6,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt2.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 450,
  },
  {
    id: 7,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant2.avif"),
    Desc: "Stylish Men's Pant",
    Price: 420,
  },
  {
    id: 8,
    title: "short",
    image: require("../../assets/images/Mens/products/short2.avif"),
    Desc: "Stylish Men's Short",
    Price: 249,
  },
  {
    id: 9,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt3.avif"),
    Desc: "Stylish Men's Shirt",
    Price: 749,
  },
  {
    id: 10,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt3.webp"),
    Desc: "Stylish Men's T-Shirt",
    Price: 329,
  },
  {
    id: 11,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant3.avif"),
    Desc: "Stylish Men's Pant",
    Price: 449,
  },
  {
    id: 12,
    title: "short",
    image: require("../../assets/images/Mens/products/short3.avif"),
    Desc: "Stylish Men's Short",
    Price: 220,
  },
  {
    id: 13,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt4.jpg"),
    Desc: "Stylish Men's Shirt",
    Price: 1000,
  },
  {
    id: 14,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt4.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 650,
  },
  {
    id: 15,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant4.webp"),
    Desc: "Stylish Men's Pant",
    Price: 450,
  },
  {
    id: 16,
    title: "short",
    image: require("../../assets/images/Mens/products/short4.avif"),
    Desc: "Stylish Men's Short",
    Price: 320,
  },
  {
    id: 17,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt5.avif"),
    Desc: "Stylish Men's Shirt",
    Price: 870,
  },
  {
    id: 18,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt5.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 620,
  },
  {
    id: 19,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant13.avif"),
    Desc: "Stylish Men's Pant",
    Price: 450,
  },
  {
    id: 20,
    title: "short",
    image: require("../../assets/images/Mens/products/short5.avif"),
    Desc: "Stylish Men's Short",
    Price: 340,
  },
  {
    id: 21,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt6.avif"),
    Desc: "Stylish Men's Shirt",
    Price: 720,
  },
  {
    id: 22,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt6.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 280,
  },
  {
    id: 23,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant5.avif"),
    Desc: "Stylish Men's Pant",
    Price: 670,
  },
  {
    id: 24,
    title: "short",
    image: require("../../assets/images/Mens/products/short6.avif"),
    Desc: "Stylish Men's Short",
    Price: 750,
  },
  {
    id: 25,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt7.avif"),
    Desc: "Stylish Men's Shirt",
    Price: 420,
  },
  {
    id: 26,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt7.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 700,
  },
  {
    id: 27,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant6.webp"),
    Desc: "Stylish Men's Pant",
    Price: 240,
  },
  {
    id: 28,
    title: "short",
    image: require("../../assets/images/Mens/products/short7.avif"),
    Desc: "Stylish Men's Short",
    Price: 340,
  },
  {
    id: 29,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt25.jpg"),
    Desc: "Stylish Men's Shirt",
    Price: 450,
  },
  {
    id: 30,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt8.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 520,
  },
  {
    id: 31,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant7.avif"),
    Desc: "Stylish Men's Pant",
    Price: 630,
  },
  {
    id: 32,
    title: "short",
    image: require("../../assets/images/Mens/products/short8.avif"),
    Desc: "Stylish Men's Short",
    Price: 470,
  },
  {
    id: 33,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt8.webp"),
    Desc: "Stylish Men's Shirt",
    Price: 520,
  },
  {
    id: 34,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt9.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 470,
  },
  {
    id: 35,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant8.avif"),
    Desc: "Stylish Men's Pant",
    Price: 750,
  },
  {
    id: 36,
    title: "short",
    image: require("../../assets/images/Mens/products/short9.avif"),
    Desc: "Stylish Men's Short",
    Price: 470,
  },
  {
    id: 37,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt9.webp"),
    Desc: "Stylish Men's Shirt",
    Price: 640,
  },
  {
    id: 38,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt10.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 540,
  },
  {
    id: 39,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant9.avif"),
    Desc: "Stylish Men's Pant",
    Price: 986,
  },
  {
    id: 40,
    title: "short",
    image: require("../../assets/images/Mens/products/short10.avif"),
    Desc: "Stylish Men's Short",
    Price: 567,
  },
  {
    id: 41,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt10.avif"),
    Desc: "Stylish Men's Shirts",
    Price: 945,
  },
  {
    id: 42,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt11.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 453,
  },
  {
    id: 43,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant10.avif"),
    Desc: "Stylish Men's Pant",
    Price: 365,
  },
  {
    id: 44,
    title: "short",
    image: require("../../assets/images/Mens/products/short11.avif"),
    Desc: "Stylish Men's Short",
    Price: 296,
  },
  {
    id: 45,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt11.jpg"),
    Desc: "Stylish Men's Shirt",
    Price: 864,
  },
  {
    id: 46,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt12.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 543,
  },
  {
    id: 47,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant11.avif"),
    Desc: "Stylish Men's Pant",
    Price: 432,
  },
  {
    id: 48,
    title: "short",
    image: require("../../assets/images/Mens/products/short12.avif"),
    Desc: "Stylish Men's Short",
    Price: 321,
  },
  {
    id: 49,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt12.jpg"),
    Desc: "Stylish Men's Shirt",
    Price: 450,
  },
  {
    id: 50,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt13.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 678,
  },
  {
    id: 51,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant12.avif"),
    Desc: "Stylish Men's Pant",
    Price: 345,
  },
  {
    id: 52,
    title: "short",
    image: require("../../assets/images/Mens/products/short13.avif"),
    Desc: "Stylish Men's Short",
    Price: 234,
  },
  {
    id: 53,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt13.jpg"),
    Desc: "Stylish Men's Shirt",
    Price: 745,
  },
  {
    id: 54,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt14.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 397,
  },
  {
    id: 55,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant14.avif"),
    Desc: "Stylish Men's Pant",
    Price: 490,
  },
  {
    id: 56,
    title: "short",
    image: require("../../assets/images/Mens/products/short14.avif"),
    Desc: "Stylish Men's Short",
    Price: 540,
  },
  {
    id: 57,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt14.jpg"),
    Desc: "Stylish Men's Shirt",
    Price: 947,
  },
  {
    id: 58,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt15.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 429,
  },
  {
    id: 59,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant15.avif"),
    Desc: "Stylish Men's Pant",
    Price: 398,
  },
  {
    id: 60,
    title: "short",
    image: require("../../assets/images/Mens/products/short15.avif"),
    Desc: "Stylish Men's Short",
    Price: 298,
  },
  {
    id: 61,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt15.avif"),
    Desc: "Stylish Men's Shirt",
    Price: 789,
  },
  {
    id: 62,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt16.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 480,
  },
  {
    id: 63,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant16.avif"),
    Desc: "Stylish Men's Pant",
    Price: 730,
  },
  {
    id: 64,
    title: "short",
    image: require("../../assets/images/Mens/products/short16.avif"),
    Desc: "Stylish Men's Short",
    Price: 830,
  },
  {
    id: 65,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt16.avif"),
    Desc: "Stylish Men's Shirt",
    Price: 950,
  },
  {
    id: 66,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt17.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 639,
  },
  {
    id: 67,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant17.webp"),
    Desc: "Stylish Men's Pant",
    Price: 920,
  },
  {
    id: 68,
    title: "short",
    image: require("../../assets/images/Mens/products/short17.avif"),
    Desc: "Stylish Men's Short",
    Price: 850,
  },
  {
    id: 69,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt17.jpg"),
    Desc: "Stylish Men's Shirt",
    Price: 849,
  },
  {
    id: 70,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt18.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 940,
  },
  {
    id: 71,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant18.avif"),
    Desc: "Stylish Men's Pant",
    Price: 820,
  },
  {
    id: 72,
    title: "short",
    image: require("../../assets/images/Mens/products/short18.avif"),
    Desc: "Stylish Men's Short",
    Price: 298,
  },
  {
    id: 73,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt18.avif"),
    Desc: "Stylish Men's Shirt",
    Price: 678,
  },
  {
    id: 74,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt19.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 840,
  },
  {
    id: 75,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant19.webp"),
    Desc: "Stylish Men's Pant",
    Price: 780,
  },
  {
    id: 76,
    title: "short",
    image: require("../../assets/images/Mens/products/short19.avif"),
    Desc: "Stylish Men's Short",
    Price: 930,
  },
  {
    id: 77,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt19.avif"),
    Desc: "Stylish Men's Shirt",
    Price: 948,
  },
  {
    id: 78,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt20.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 928,
  },
  {
    id: 79,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant20.webp"),
    Desc: "Stylish Men's Pant",
    Price: 748,
  },
  {
    id: 80,
    title: "short",
    image: require("../../assets/images/Mens/products/short20.avif"),
    Desc: "Stylish Men's Short",
    Price: 564,
  },
  {
    id: 81,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt20.webp"),
    Desc: "Stylish Men's Shirt",
    Price: 879,
  },
  {
    id: 82,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt21.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 299,
  },
  {
    id: 83,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant21.avif"),
    Desc: "Stylish Men's Pant",
    Price: 845,
  },
  {
    id: 84,
    title: "short",
    image: require("../../assets/images/Mens/products/short21.avif"),
    Desc: "Stylish Men's Short",
    Price: 907,
  },
  {
    id: 85,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt21.avif"),
    Desc: "Stylish Men's Shirt",
    Price: 748,
  },
  {
    id: 86,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt22.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 936,
  },
  {
    id: 87,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant22.avif"),
    Desc: "Stylish Men's Pant",
    Price: 573,
  },
  {
    id: 88,
    title: "short",
    image: require("../../assets/images/Mens/products/short22.avif"),
    Desc: "Stylish Men's Short",
    Price: 298,
  },
  {
    id: 89,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt22.jpg"),
    Desc: "Stylish Men's Shirt",
    Price: 639,
  },
  {
    id: 90,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt23.jpg"),
    Desc: "Stylish Men's T-Shirt",
    Price: 599,
  },
  {
    id: 91,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant23.avif"),
    Desc: "Stylish Men's Pant",
    Price: 300,
  },
  {
    id: 92,
    title: "short",
    image: require("../../assets/images/Mens/products/short23.avif"),
    Desc: "Stylish Men's Short",
    Price: 450,
  },
  {
    id: 93,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt23.avif"),
    Desc: "Stylish Men's Shirt",
    Price: 739,
  },
  {
    id: 94,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt24.avif"),
    Desc: "Stylish Men's T-Shirt",
    Price: 938,
  },
  {
    id: 95,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant24.avif"),
    Desc: "Stylish Men's Pant",
    Price: 394,
  },
  {
    id: 96,
    title: "short",
    image: require("../../assets/images/Mens/products/short24.avif"),
    Desc: "Stylish Men's Short",
    Price: 310,
  },
  {
    id: 97,
    title: "shirt",
    image: require("../../assets/images/Mens/products/shirt24.avif"),
    Desc: "Stylish Men's Shirt",
    Price: 420,
  },
  {
    id: 98,
    title: "tshirt",
    image: require("../../assets/images/Mens/products/tshirt25.jpg"),
    Desc: "Stylish Men's T-Shirt",
    Price: 270,
  },
  {
    id: 99,
    title: "pant",
    image: require("../../assets/images/Mens/products/pant25.webp"),
    Desc: "Stylish Men's Pant",
    Price: 839,
  },
  //   {
  //     id: 100,
  //     title: "short",
  //     image: require("../../assets/images/Mens/products/short25.avif"),
  //     Desc: "Stylish Men's Short",
  //     Price: 480,
  //   },
];
